site_name: BFS Component Library
nav:
  - Home: index.md
  - API: api.md
  - Examples: examples.md
  - Components:
    - Card: components_cards.md
    - Inputs: components_inputs.md
theme: readthedocs
