[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "bfs-component-library"
version = "0.1.0"
description = "A small BFS component library in Python"
authors = [ { name = "Your Name" } ]
dependencies = []
